import Head from "next/head";
import { Space_Grotesk } from "@next/font/google";
import { useState } from "react";
import Header from "@/components/Header";
import { motion } from "framer-motion";
import Overlay from "@/components/Overlay";

const SpaceGrotesk = Space_Grotesk({ subsets: ["latin"] });

export default function Home() {
  const text = "Crafting Timeless Styles: Where Excellence Meets Elegance.";
  const textChars = text.split("");
  return (
    <>
      <Head>
        <title>Jedi Salon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="w-full h-screen bg-no-repeat bg-cover bg-hero font-body">
        <Overlay />
        <div className="container relative z-10 flex items-end h-screen pb-20 mx-auto">
          <motion.h1 className="w-1/2 font-bold text-white uppercase text-7xl text-clip">
            {textChars.map((char, i) => (
              <motion.span
                initial={{ opacity: 0, y: '10%'  }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.3, ease: "easeIn" }}
                key={i}
                className="text-clip bg-clip-content"
              >
                {char}
              </motion.span>
            ))}
          </motion.h1>
        </div>
      </main>
    </>
  );
}
/* <Modal isOpen={isOpen}  setIsOpen={setIsOpen} >Hello there</Modal> */
